apiVersion: v1
kind: Pod
metadata:
  name: mypod
spec:
  containers:
  - name: myngninx
    image: nginx
    volumeMounts:
    - name: mycred
      mountPath: "/data/"
      readOnly: true
  volumes:
  - name: mycred
    secret:
      secretName: secret-test
