apiVersion: v1
kind: Pod
metadata:
  name: init-container-test
spec:
  containers:
  - name: application-container
    image: alpine
    command: ['sh', '-c', 'if [ -f /data/hungry.txt ]; then sleep 99999; else exit; fi']
    volumeMounts:
    - name: workdir-volume
      mountPath: /data
  initContainers:
  - name: init-container
    image: redis
    command: ['sh', '-c', 'mkdir /data; echo>/data/hungry.txt']
    volumeMounts:
    - name: workdir-volume
      mountPath: /data
  volumes:
  - name: workdir-volume
    emptyDir: {}
