apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: 'redis-label'
spec:
 selector:
    matchLabels:
     node: nginx
 template:
   metadata:
      labels:
        name: redis-label
   spec:
    containers:
    - name: nginx
      image: nginx

