apiVersion: v1
kind: Pod
metadata:
        name: mypodtask9
spec:
  containers:
  - name: mynginx
    image: nginx
    env:
      - name: CREDENTIAL
        valueFrom:
          secretKeyRef:
            name: secret-test
            key: credential
